# Generated by Django 4.2.5 on 2023-09-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
